### ISSUE TITLE
Wrong Network Adapter

### ISSUE THREAD

**Issue by ramsayk3** [covcom/303CEM#3]
Networking worksheet- 3.1 - `enp0s8` should be `enp0s3` for the server and webserver. The Gateway text above on the worksheet stays as `enp0s8` .

```
#The primary network interface
auto enp0s8
iface enp0s8 inet static
address 192.168.56.xxx      #replace xxx with appropriate numbers such as 101, 102 etc.
network 192.168.56.0
broadcast 192.168.56.255
gateway 192.168.56.103
```

**Comment by marktyers** [comment]
Instructions are now fixed, removed any ambiguity in following sections.
